model_name: unet_test
epochs: 5
batch_size: 32

model_class: UNet2DModel
model_params:
  - sample_size
  - layers_per_block
  - block_out_channels
  - down_block_types
  - up_block_types

sample_size: 128
layers_per_block: 2
block_out_channels:
  - 128
  - 128
  - 256
  - 256
  - 512
  - 512
down_block_types:
  - "DownBlock2D"  # a regular ResNet downsampling block
  - "DownBlock2D"
  - "DownBlock2D"
  - "DownBlock2D"
  - "AttnDownBlock2D"  # a ResNet downsampling block with spatial self-attention
  - "DownBlock2D"
up_block_types:
  - "UpBlock2D"  # a regular ResNet upsampling block
  - "AttnUpBlock2D"  # a ResNet upsampling block with spatial self-attention
  - "UpBlock2D"
  - "UpBlock2D"
  - "UpBlock2D"
  - "UpBlock2D"

lr: 0.0001
lr_warmup_steps: 500
image_size: 128
